name: build

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '.github/workflows/build.yaml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/build.yaml'

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: config.kibot.yaml
        # # optional - prefix to output defined in config
        # dir: output
        # # optional - schematic file
        # schema: 'schematic.sch'
        # # optional - PCB design file
        # board: 'pcb.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: export
        path: export
    - name: Commit results
        run: |
          git config --global user.name 'Torsten Wylegala'
          git config --global user.email 'twyleg@users.noreply.github.com'
          git commit -am "Generated exports"
          git push
