name: build

on:
  push:
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '.github/workflows/build.yaml'
    - 'config.kibot.yaml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/build.yaml'
      - 'config.kibot.yaml'

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Clean exports
      run: rm -r ./export/
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: default.kibot.yaml

